### PR TITLE
Allow building with more recent dependencies

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by cartazio** [comment]
Awesome! I'll take some time and review this over the next few days.

**Comment by AlainODea** [comment]
Hi @bgamari, thank you :)

I'm going to give this a spin tomorrow. I set up multiple GHC versions on Ubuntu and SmartOS to validate this with this evening, but I ran out of steam before trying your change.

**Comment by cartazio** [comment]
Derp I totally dropped the ball too

**Comment by AlainODea** [comment]
I've verified that this builds cleanly and basic tests work on Ubuntu 14.04 and SmartOS base-multiarch 15.3.0.  Thank you @bgamari.

**Pull request merged**
